CREATE OR ALTER PROCEDURE SP_ACTUALIZA_LOG_RECONCILIACION @RECNUM_DEUDOR NVARCHAR(100), @RECNUM_ACREEDOR NVARCHAR(100)
AS
BEGIN
	UPDATE LOG_RECONCILIACION
	SET ESTADO = 'C'
	WHERE NUMRECON_ACREEDOR = @RECNUM_ACREEDOR  AND NUMRECON_DEUDOR = @RECNUM_DEUDOR
END 