CREATE OR ALTER PROCEDURE SP_ACTUALIZA_LOG_DEVOLUCION @DOCNUM_PP NVARCHAR(100), @DOCNUM_PR NVARCHAR(100)
AS
BEGIN
	UPDATE LOG_DEVOLUCIONES
	SET ESTADO = 'C'
	WHERE DOCNUM_PP = @DOCNUM_PP  AND DOCNUM_PR = @DOCNUM_PR
END 
