CREATE OR ALTER PROCEDURE [dbo].[SP_ACTUALIZA_LOG_PRESTAMOS] @DOCNUM_PP NVARCHAR(100), @DOCNUM_PR NVARCHAR(100)
AS
BEGIN
	UPDATE LOG_PRESTAMOS
	SET ESTADO = 'C'
	WHERE DOCNUM_PP = @DOCNUM_PP  AND DOCNUM_PR = @DOCNUM_PR
END 
