CREATE PROCEDURE SP_CONSULTA_DATABASE
AS
BEGIN

	DECLARE @COUNT INT = 1, @SIZE INT
	DECLARE @TABLA TABLE(
		Id INT IDENTITY(1,1),
		DataBaseName NVARCHAR(200)
	)
	DECLARE @TABLA_DB TABLE(
		DataBaseName NVARCHAR(200),
		RazonSocial NVARCHAR(200)
	)

	INSERT INTO @TABLA
	SELECT  name
	FROM sys.databases
	WHERE NAME NOT IN ('master', 'model', 'msdb', 'tempdb', 'Z_SBO_MIMSA_31072025', 'Z_SBO_INDUZINC_20072025', 'Z_SBO_MEGA_29072025')
	AND name LIKE '%SBO%'
	ORDER BY name;

	SET @SIZE = (SELECT COUNT(*) FROM @TABLA)

	WHILE @COUNT <= @SIZE
	BEGIN
	
		DECLARE @DataBase NVARCHAR(200)  = (SELECT DataBaseName FROM @TABLA WHERE Id = @COUNT)

		BEGIN TRY
			DECLARE @TEXT NVARCHAR(MAX) = 'SELECT ''' + @DataBase + ''' DataBaseName, UPPER(PrintHeadr) RazonSocial FROM ['+ @DataBase +'].dbo.OADM '
			INSERT INTO @TABLA_DB
			EXECUTE (@TEXT)
		END TRY
		BEGIN CATCH
		END CATCH;

		SET @COUNT += 1
	END

	SELECT * FROM @TABLA_DB
END