CREATE OR ALTER PROCEDURE [dbo].[SP_DEVOLUCION_RECONCILIACION] @PRESTAMO NVARCHAR(20), @BANCO NVARCHAR(20)
AS
BEGIN
	--DECLARE @PRESTAMO NVARCHAR(20) = '207380'
	--DECLARE @BANCO NVARCHAR(20) = '104102'

	SELECT T0.TransId, T4.Line_ID, IIF(ISNULL(T0.DocCurr,'SOL') = 'SOL', T1.SumApplied, T1.AppliedFC) Monto
	FROM OVPM T0 INNER JOIN VPM4 T1 ON T0.DocEntry = T1.DocNum
				INNER JOIN OJDT T3 ON T0.TransId = T3.TransId
				INNER JOIN JDT1 T4 ON T3.TransId = T4.TransId
	WHERE T1.U_GMI_PAGORELACION = @PRESTAMO
	AND T4.Account = @BANCO
	AND T1.AcctCode = '471003' /* CUENTA DE PRESTAMOS */
	AND T0.Canceled = 'N'
	UNION
	SELECT T0.TransId, T4.Line_ID, IIF(ISNULL(T0.DocCurr,'SOL') = 'SOL', T1.SumApplied, T1.AppliedFC) Monto
	FROM ORCT T0 INNER JOIN RCT4 T1 ON T0.DocEntry = T1.DocNum
				INNER JOIN OJDT T3 ON T0.TransId = T3.TransId
				INNER JOIN JDT1 T4 ON T3.TransId = T4.TransId
	WHERE T1.U_GMI_PAGORELACION = @PRESTAMO
	AND T4.Account = @BANCO
	AND T1.AcctCode = '471003'
	AND T0.Canceled = 'N'
END