CREATE OR ALTER PROCEDURE SP_LOG_RECONCILIACION @NUMRECON_PRESTAMO NVARCHAR(100), @EMPRESA_PRESTAMO NVARCHAR(120), @NUMRECON_DEUDOR NVARCHAR(100), @EMPRESA_DEUDOR NVARCHAR(120)
AS
BEGIN

--CREATE TABLE LOG_RECONCILIACION(
	--ID INT IDENTITY(1,1),
	--NRO_PRESTAMO NVARCHAR(30),
	--NUMRECON_ACREEDOR NVARCHAR(100),
	--EMPRESA_ACREEDOR NVARCHAR(120),
	--NUMRECON_DEUDOR NVARCHAR(100),
	--EMPRESA_DEUDOR NVARCHAR(120),
	--ESTADO NCHAR(1) DEFAULT 'A',
	--FECHA_REGISTRO DATETIME DEFAULT GETDATE()
	--)

	INSERT INTO LOG_RECONCILIACION (NRO_PRESTAMO, NUMRECON_ACREEDOR, EMPRESA_ACREEDOR, NUMRECON_DEUDOR, EMPRESA_DEUDOR) 
	VALUES (@NRO_PRESTAMO, @NUMRECON_PRESTAMO, @EMPRESA_PRESTAMO, @NUMRECON_DEUDOR, @EMPRESA_DEUDOR)

END