CREATE OR ALTER PROCEDURE SP_LOG_PRESTAMOS @EMPRESA_PP NVARCHAR(120), @DOCNUM_PP NVARCHAR(100), @EMPRESA_PR NVARCHAR(120), @DOCNUM_PR NVARCHAR(100)
AS
BEGIN
	--CREATE TABLE LOG_PRESTAMOS(
	--ID INT IDENTITY(1,1),
	--EMPRESA_PP NVARCHAR(120),
	--DOCNUM_PP NVARCHAR(100),
	--EMPRESA_PR NVARCHAR(120),
	--DOCNUM_PR NVARCHAR(100),
	--ESTADO CHAR(1) DEFAULT 'A',
	--FECHA_REGISTRO DATETIME DEFAULT GETDATE()
	--)

	INSERT INTO LOG_PRESTAMOS (EMPRESA_PP, DOCNUM_PP, EMPRESA_PR, DOCNUM_PR) VALUES (@EMPRESA_PP, @DOCNUM_PP, @EMPRESA_PR, @DOCNUM_PR)

END