CREATE OR ALTER PROCEDURE SP_LOG_DEVOLUCIONES @NRO_PRESTAMO NVARCHAR(120), @EMPRESA_PP NVARCHAR(120), @DOCNUM_PP NVARCHAR(100), @EMPRESA_PR NVARCHAR(120), @DOCNUM_PR NVARCHAR(100)
AS
BEGIN

	--CREATE TABLE LOG_DEVOLUCIONES(
	--ID INT IDENTITY(1,1),
	--NRO_PRESTAMO NVARCHAR(30),
	--EMPRESA_PP NVARCHAR(120),
	--DOCNUM_PP NVARCHAR(100),
	--EMPRESA_PR NVARCHAR(120),
	--DOCNUM_PR NVARCHAR(100),
	--ESTADO CHAR(1) DEFAULT 'A',
	--FECHA_REGISTRO DATETIME DEFAULT GETDATE()
	--)

	INSERT INTO LOG_DEVOLUCIONES (NRO_PRESTAMO, EMPRESA_PP, DOCNUM_PP, EMPRESA_PR, DOCNUM_PR) VALUES (@NRO_PRESTAMO, @EMPRESA_PP, @DOCNUM_PP, @EMPRESA_PR, @DOCNUM_PR)

END