CREATE OR ALTER PROCEDURE [dbo].[SP_VISUALIZAR_LOG_RECONCILIACION] @Nro_Prestamo NVARCHAR(100)
AS
BEGIN
	--SELECT * FROM LOG_DEVOLUCIONES
	SELECT NUMRECON_ACREEDOR 'Nro Recon. Acreedor', NUMRECON_DEUDOR 'Nro Recon. Deudor' 
	FROM LOG_RECONCILIACION
	WHERE NRO_PRESTAMO = @Nro_Prestamo
	AND ESTADO = 'A'
END