CREATE OR ALTER PROCEDURE [dbo].[SP_VISUALIZAR_LOG_PRESTAMOS] @Nro_Prestamo NVARCHAR(100)
AS
BEGIN
	SELECT DOCNUM_PP 'Nro Prestamo PP', DOCNUM_PR 'Nro Prestamo PR' 
	FROM LOG_PRESTAMOS
	WHERE DOCNUM_PP = @Nro_Prestamo
	AND ESTADO = 'A'
END