CREATE OR ALTER PROCEDURE [dbo].[SP_VISUALIZAR_LOG_DEVOLUCIONES] @Nro_Prestamo NVARCHAR(100)
AS
BEGIN
	--SELECT * FROM LOG_DEVOLUCIONES
	SELECT DOCNUM_PP 'Nro Devolucion PP', DOCNUM_PR 'Nro Devolucion PR' 
	FROM LOG_DEVOLUCIONES
	WHERE NRO_PRESTAMO = @Nro_Prestamo
	AND ESTADO = 'A'
END

